/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Price } from "./Price";
import { PriceCountArgs } from "./PriceCountArgs";
import { PriceFindManyArgs } from "./PriceFindManyArgs";
import { PriceFindUniqueArgs } from "./PriceFindUniqueArgs";
import { CreatePriceArgs } from "./CreatePriceArgs";
import { UpdatePriceArgs } from "./UpdatePriceArgs";
import { DeletePriceArgs } from "./DeletePriceArgs";
import { Cryptocurrency } from "../../cryptocurrency/base/Cryptocurrency";
import { Exchange } from "../../exchange/base/Exchange";
import { PriceService } from "../price.service";
@graphql.Resolver(() => Price)
export class PriceResolverBase {
  constructor(protected readonly service: PriceService) {}

  async _pricesMeta(
    @graphql.Args() args: PriceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Price])
  async prices(@graphql.Args() args: PriceFindManyArgs): Promise<Price[]> {
    return this.service.prices(args);
  }

  @graphql.Query(() => Price, { nullable: true })
  async price(
    @graphql.Args() args: PriceFindUniqueArgs
  ): Promise<Price | null> {
    const result = await this.service.price(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Price)
  async createPrice(@graphql.Args() args: CreatePriceArgs): Promise<Price> {
    return await this.service.createPrice({
      ...args,
      data: {
        ...args.data,

        cryptocurrency: args.data.cryptocurrency
          ? {
              connect: args.data.cryptocurrency,
            }
          : undefined,

        exchange: args.data.exchange
          ? {
              connect: args.data.exchange,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Price)
  async updatePrice(
    @graphql.Args() args: UpdatePriceArgs
  ): Promise<Price | null> {
    try {
      return await this.service.updatePrice({
        ...args,
        data: {
          ...args.data,

          cryptocurrency: args.data.cryptocurrency
            ? {
                connect: args.data.cryptocurrency,
              }
            : undefined,

          exchange: args.data.exchange
            ? {
                connect: args.data.exchange,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Price)
  async deletePrice(
    @graphql.Args() args: DeletePriceArgs
  ): Promise<Price | null> {
    try {
      return await this.service.deletePrice(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Cryptocurrency, {
    nullable: true,
    name: "cryptocurrency",
  })
  async getCryptocurrency(
    @graphql.Parent() parent: Price
  ): Promise<Cryptocurrency | null> {
    const result = await this.service.getCryptocurrency(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Exchange, {
    nullable: true,
    name: "exchange",
  })
  async getExchange(@graphql.Parent() parent: Price): Promise<Exchange | null> {
    const result = await this.service.getExchange(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => String)
  async FetchPrices(
    @graphql.Args()
    args: string
  ): Promise<string> {
    return this.service.FetchPrices(args);
  }
}
