/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CryptocurrencyService } from "../cryptocurrency.service";
import { CryptocurrencyCreateInput } from "./CryptocurrencyCreateInput";
import { Cryptocurrency } from "./Cryptocurrency";
import { CryptocurrencyFindManyArgs } from "./CryptocurrencyFindManyArgs";
import { CryptocurrencyWhereUniqueInput } from "./CryptocurrencyWhereUniqueInput";
import { CryptocurrencyUpdateInput } from "./CryptocurrencyUpdateInput";
import { PriceFindManyArgs } from "../../price/base/PriceFindManyArgs";
import { Price } from "../../price/base/Price";
import { PriceWhereUniqueInput } from "../../price/base/PriceWhereUniqueInput";

export class CryptocurrencyControllerBase {
  constructor(protected readonly service: CryptocurrencyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Cryptocurrency })
  async createCryptocurrency(
    @common.Body() data: CryptocurrencyCreateInput
  ): Promise<Cryptocurrency> {
    return await this.service.createCryptocurrency({
      data: data,
      select: {
        createdAt: true,
        id: true,
        name: true,
        symbolField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Cryptocurrency] })
  @ApiNestedQuery(CryptocurrencyFindManyArgs)
  async cryptocurrencies(
    @common.Req() request: Request
  ): Promise<Cryptocurrency[]> {
    const args = plainToClass(CryptocurrencyFindManyArgs, request.query);
    return this.service.cryptocurrencies({
      ...args,
      select: {
        createdAt: true,
        id: true,
        name: true,
        symbolField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Cryptocurrency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async cryptocurrency(
    @common.Param() params: CryptocurrencyWhereUniqueInput
  ): Promise<Cryptocurrency | null> {
    const result = await this.service.cryptocurrency({
      where: params,
      select: {
        createdAt: true,
        id: true,
        name: true,
        symbolField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Cryptocurrency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCryptocurrency(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() data: CryptocurrencyUpdateInput
  ): Promise<Cryptocurrency | null> {
    try {
      return await this.service.updateCryptocurrency({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          name: true,
          symbolField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Cryptocurrency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCryptocurrency(
    @common.Param() params: CryptocurrencyWhereUniqueInput
  ): Promise<Cryptocurrency | null> {
    try {
      return await this.service.deleteCryptocurrency({
        where: params,
        select: {
          createdAt: true,
          id: true,
          name: true,
          symbolField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/prices")
  @ApiNestedQuery(PriceFindManyArgs)
  async findPrices(
    @common.Req() request: Request,
    @common.Param() params: CryptocurrencyWhereUniqueInput
  ): Promise<Price[]> {
    const query = plainToClass(PriceFindManyArgs, request.query);
    const results = await this.service.findPrices(params.id, {
      ...query,
      select: {
        createdAt: true,

        cryptocurrency: {
          select: {
            id: true,
          },
        },

        exchange: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,
        timestamp: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/prices")
  async connectPrices(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() body: PriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prices: {
        connect: body,
      },
    };
    await this.service.updateCryptocurrency({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/prices")
  async updatePrices(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() body: PriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prices: {
        set: body,
      },
    };
    await this.service.updateCryptocurrency({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/prices")
  async disconnectPrices(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() body: PriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      prices: {
        disconnect: body,
      },
    };
    await this.service.updateCryptocurrency({
      where: params,
      data,
      select: { id: true },
    });
  }
}
